gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "My name is OAK.\p"
	.string "People call me the Pokémon\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as Pokémon.\p"
	.string "People and Pokémon live together,\n"
	.string "by supporting each other.\p"
	.string "Some people play with Pokémon,\n"
	.string "some battle with them. \p"
	.string "But we don't know everything about\n"
	.string "Pokémon yet. \p"
	.string "There are still many mysteries\n"
	.string "to solve. That's why I study\l"
	.string "Pokémon every day.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "{PLAYER}{KUN}, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "You'll face fun times and tough\n"
	.string "challenges.\p"
	.string "A world of dreams and adventures\n"
	.string "with Pokémon awaits! Let's go!\p"
	.string "I'll be seeing you later!\p"
	.string "$"

gText_Birch_Farewell::
	.string "You'll face fun times and tough\n"
	.string "challenges.\p"
	.string "A world of dreams and adventures\n"
	.string "with Pokémon awaits! Let's go!\p"
	.string "I'll be seeing you later!\p"
	.string "$"
