# 1 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 2 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 3 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodRaidoTower2_EventScript_Grunt3::
# 4 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_3 GoldenrodCity_RadioTower_2F_Text_GruntM4Seen, GoldenrodCity_RadioTower_2F_Text_GruntM4Beaten
# 5 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_GruntM4After, MSGBOX_AUTOCLOSE
# 6 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	end
# 7 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodRaidoTower2_EventScript_Grunt4::
# 8 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_4 GoldenrodCity_RadioTower_2F_Text_GruntM5Seen, GoldenrodCity_RadioTower_2F_Text_GruntM5Beaten
# 9 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_GruntM5After, MSGBOX_AUTOCLOSE
# 10 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	end
# 11 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodRaidoTower2_EventScript_Grunt5::
# 12 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_5 GoldenrodCity_RadioTower_2F_Text_GruntM6Seen, GoldenrodCity_RadioTower_2F_Text_GruntM6Beaten
# 13 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_GruntM6After, MSGBOX_AUTOCLOSE
# 14 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	end
# 15 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodRaidoTower2_EventScript_GruntF2::
# 16 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_26 GoldenrodCity_RadioTower_2F_Text_GruntF2Seen, GoldenrodCity_RadioTower_2F_Text_GruntF2Beaten
# 17 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_GruntF2After, MSGBOX_AUTOCLOSE
# 18 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	end
# 19 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 20 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_Sign1::
# 21 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	lock
# 22 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_SalesSign, MSGBOX_SIGN
# 23 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	closemessage
# 24 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	release
# 25 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	end
# 26 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 27 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_Sign2::
# 28 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	lock
# 29 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_OakTalkSign, MSGBOX_SIGN
# 30 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	closemessage
# 31 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	release
# 32 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	end
# 33 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 34 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_Boy::
# 35 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	lock
# 36 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	faceplayer
# 37 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_SuperNerd, MSGBOX_DEFAULT
# 38 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	closemessage
# 39 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	release
# 40 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	end
# 41 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 42 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_Policeman::
# 43 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	lock
# 44 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	faceplayer
# 45 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_Policeman, MSGBOX_DEFAULT
# 46 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	closemessage
# 47 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	release
# 48 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	end
# 49 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 50 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_Buena::
# 51 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	lock
# 52 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	faceplayer
# 53 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto_if_eq VAR_GOLDENROD_CITY_STATE, 6, GoldenrodCity_RadioTower_2F_EventScript_Buena2
# 54 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto_if_eq VAR_GOLDENROD_CITY_STATE, 7, GoldenrodCity_RadioTower_2F_EventScript_Buena2
# 55 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto_if_eq VAR_GOLDENROD_CITY_STATE, 8, GoldenrodCity_RadioTower_2F_EventScript_Buena2
# 56 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto_if_eq VAR_GOLDENROD_CITY_STATE, 9, GoldenrodCity_RadioTower_2F_EventScript_Buena2
# 57 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto_if_unset FLAG_ENABLE_RADIO, GoldenrodCity_RadioTower_2F_EventScript_BuenaNoRadio
# 58 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_BuenaGreeting, MSGBOX_DEFAULT
# 59 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	dynmultichoice 0, 0, FALSE, 3, 0, DYN_MULTICHOICE_CB_NONE, GoldenrodCity_RadioTower_2F_Text_BuenaMenuPassword, GoldenrodCity_RadioTower_2F_Text_BuenaMenuPrizes, GoldenrodCity_RadioTower_2F_Text_BuenaMenuCancel
# 60 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	switch VAR_RESULT
# 61 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	case 0, GoldenrodCity_RadioTower_2F_EventScript_BuenaPassword
# 62 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	case 1, GoldenrodCity_RadioTower_2F_EventScript_BuenaPrizes
# 63 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	case 2, GoldenrodCity_RadioTower_2F_EventScript_BuenaDone
# 64 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	case MULTI_B_PRESSED, GoldenrodCity_RadioTower_2F_EventScript_BuenaDone
# 65 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	end
# 66 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 67 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaNoRadio::
# 68 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_BuenaShowPromo, MSGBOX_DEFAULT
# 69 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	closemessage
# 70 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	release
# 71 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	end
# 72 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 73 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_Buena2::
# 74 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox RadioTower2FBuenaPasswordIsHelpText, MSGBOX_DEFAULT
# 75 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	closemessage
# 76 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	release
# 77 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	end
# 78 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 79 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaPassword::
# 80 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	specialvar VAR_RESULT, BuenasPassword_IsBroadcastTime
# 81 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto_if_eq VAR_RESULT, FALSE, GoldenrodCity_RadioTower_2F_EventScript_BuenaOffAir
# 82 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto_if_set FLAG_DAILY_BUENA_PASSWORD, GoldenrodCity_RadioTower_2F_EventScript_BuenaAlreadyPlayed
# 83 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	special BuenasPassword_BufferCurrentPassword
# 84 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_BuenaAskPassword, MSGBOX_YESNO
# 85 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto_if_eq VAR_RESULT, NO, GoldenrodCity_RadioTower_2F_EventScript_BuenaForgotPassword
# 86 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_BuenaJoinShow, MSGBOX_DEFAULT
# 87 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	closemessage
# 88 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	turnobject LOCALID_BUENA, DIR_EAST
# 89 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	moveobjecttocoords LOCALID_PLAYER, 28, 15, DIR_EAST
# 90 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	waitmovement 0
# 91 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_BuenaEveryoneReady, MSGBOX_DEFAULT
# 92 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	specialvar VAR_0x8004, BuenasPassword_GetCurrentGroup
# 93 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	switch VAR_0x8004
# 94 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	case 0, GoldenrodCity_RadioTower_2F_EventScript_BuenaAskStarters
# 95 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	case 1, GoldenrodCity_RadioTower_2F_EventScript_BuenaAskMedicine
# 96 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	case 2, GoldenrodCity_RadioTower_2F_EventScript_BuenaAskBalls
# 97 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	case 3, GoldenrodCity_RadioTower_2F_EventScript_BuenaAskRouteMons
# 98 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	case 4, GoldenrodCity_RadioTower_2F_EventScript_BuenaAskNightMons
# 99 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	case 5, GoldenrodCity_RadioTower_2F_EventScript_BuenaAskTowns
# 100 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	case 6, GoldenrodCity_RadioTower_2F_EventScript_BuenaAskCategories
# 101 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	case 7, GoldenrodCity_RadioTower_2F_EventScript_BuenaAskMoves
# 102 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	case 8, GoldenrodCity_RadioTower_2F_EventScript_BuenaAskXItems
# 103 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	case 9, GoldenrodCity_RadioTower_2F_EventScript_BuenaAskRadioShows
# 104 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	end
# 105 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 106 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaForgotPassword::
# 107 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_BuenaForgotPassword, MSGBOX_DEFAULT
# 108 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaDone
# 109 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 110 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaAskStarters::
# 111 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	dynmultichoice 0, 0, TRUE, 3, 0, DYN_MULTICHOICE_CB_NONE, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerCyndaquil, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerTotodile, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerChikorita
# 112 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaCheckAnswer
# 113 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 114 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaAskMedicine::
# 115 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	dynmultichoice 0, 0, TRUE, 3, 0, DYN_MULTICHOICE_CB_NONE, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerPotion, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerAntidote, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerParlyzHeal
# 116 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaCheckAnswer
# 117 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 118 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaAskBalls::
# 119 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	dynmultichoice 0, 0, TRUE, 3, 0, DYN_MULTICHOICE_CB_NONE, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerPokeBall, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerGreatBall, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerUltraBall
# 120 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaCheckAnswer
# 121 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 122 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaAskRouteMons::
# 123 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	dynmultichoice 0, 0, TRUE, 3, 0, DYN_MULTICHOICE_CB_NONE, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerPikachu, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerRattata, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerGeodude
# 124 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaCheckAnswer
# 125 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 126 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaAskNightMons::
# 127 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	dynmultichoice 0, 0, TRUE, 3, 0, DYN_MULTICHOICE_CB_NONE, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerHoothoot, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerSpinarak, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerDrowzee
# 128 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaCheckAnswer
# 129 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 130 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaAskTowns::
# 131 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	dynmultichoice 0, 0, TRUE, 3, 0, DYN_MULTICHOICE_CB_NONE, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerNewBarkTown, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerCherrygroveCity, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerAzaleaTown
# 132 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaCheckAnswer
# 133 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 134 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaAskCategories::
# 135 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	dynmultichoice 0, 0, TRUE, 3, 0, DYN_MULTICHOICE_CB_NONE, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerBugPokemon, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerBirdPokemon, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerGrassPokemon
# 136 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaCheckAnswer
# 137 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 138 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaAskMoves::
# 139 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	dynmultichoice 0, 0, TRUE, 3, 0, DYN_MULTICHOICE_CB_NONE, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerTackle, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerGrowl, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerMudSlap
# 140 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaCheckAnswer
# 141 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 142 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaAskXItems::
# 143 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	dynmultichoice 0, 0, TRUE, 3, 0, DYN_MULTICHOICE_CB_NONE, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerXAttack, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerXDefend, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerXSpeed
# 144 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaCheckAnswer
# 145 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 146 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaAskRadioShows::
# 147 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	dynmultichoice 0, 0, TRUE, 3, 0, DYN_MULTICHOICE_CB_NONE, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerPokemonTalk, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerPokemonMusic, GoldenrodCity_RadioTower_2F_Text_BuenaAnswerBuenasPassword
# 148 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaCheckAnswer
# 149 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 150 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaCheckAnswer::
# 151 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto_if_eq VAR_RESULT, MULTI_B_PRESSED, GoldenrodCity_RadioTower_2F_EventScript_BuenaDone
# 152 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	specialvar VAR_0x8004, BuenasPassword_GetCorrectAnswer
# 153 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	setflag FLAG_DAILY_BUENA_PASSWORD
# 154 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto_if_eq VAR_RESULT, VAR_0x8004, GoldenrodCity_RadioTower_2F_EventScript_BuenaCorrect
# 155 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_BuenaWrong, MSGBOX_DEFAULT
# 156 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaDone
# 157 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 158 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaCorrect::
# 159 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	addvar VAR_BUENA_POINTS, 1
# 160 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	addvar VAR_BUENA_PASSWORDS_CORRECT, 1
# 161 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	special Achievement_CheckAll
# 162 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	buffernumberstring STR_VAR_1, VAR_BUENA_POINTS
# 163 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	turnobject LOCALID_BUENA, DIR_SOUTH
# 164 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	playfanfare(MUS_OBTAIN_ITEM)
# 165 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_BuenaCorrect, MSGBOX_DEFAULT
# 166 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	waitfanfare
# 167 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaDone
# 168 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 169 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaOffAir::
# 170 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_BuenaOffAir, MSGBOX_DEFAULT
# 171 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaDone
# 172 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 173 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaAlreadyPlayed::
# 174 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_BuenaAlreadyPlayed, MSGBOX_DEFAULT
# 175 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaDone
# 176 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 177 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaPrizes::
# 178 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	buffernumberstring STR_VAR_1, VAR_BUENA_POINTS
# 179 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_BuenaPrizeIntro, MSGBOX_DEFAULT
# 180 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 181 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaPrizeMenu::
# 182 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	dynmultichoice 0, 0, FALSE, 6, 0, DYN_MULTICHOICE_CB_NONE, GoldenrodCity_RadioTower_2F_Text_BuenaPrizeQuickBall, GoldenrodCity_RadioTower_2F_Text_BuenaPrizeFullRestore, GoldenrodCity_RadioTower_2F_Text_BuenaPrizeElixir, GoldenrodCity_RadioTower_2F_Text_BuenaPrizeMaxElixir, GoldenrodCity_RadioTower_2F_Text_BuenaPrizeNugget, GoldenrodCity_RadioTower_2F_Text_BuenaPrizeExpCandyL, GoldenrodCity_RadioTower_2F_Text_BuenaPrizeEviolite, GoldenrodCity_RadioTower_2F_Text_BuenaPrizePPMax, GoldenrodCity_RadioTower_2F_Text_BuenaPrizeAbilityPatch, GoldenrodCity_RadioTower_2F_Text_BuenaMenuCancel
# 183 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	switch VAR_RESULT
# 184 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	case 0, GoldenrodCity_RadioTower_2F_EventScript_BuenaPrizeQuickBall
# 185 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	case 1, GoldenrodCity_RadioTower_2F_EventScript_BuenaPrizeFullRestore
# 186 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	case 2, GoldenrodCity_RadioTower_2F_EventScript_BuenaPrizeElixir
# 187 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	case 3, GoldenrodCity_RadioTower_2F_EventScript_BuenaPrizeMaxElixir
# 188 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	case 4, GoldenrodCity_RadioTower_2F_EventScript_BuenaPrizeNugget
# 189 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	case 5, GoldenrodCity_RadioTower_2F_EventScript_BuenaPrizeExpCandyL
# 190 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	case 6, GoldenrodCity_RadioTower_2F_EventScript_BuenaPrizeEviolite
# 191 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	case 7, GoldenrodCity_RadioTower_2F_EventScript_BuenaPrizePPMax
# 192 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	case 8, GoldenrodCity_RadioTower_2F_EventScript_BuenaPrizeAbilityPatch
# 193 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	case 9, GoldenrodCity_RadioTower_2F_EventScript_BuenaDone
# 194 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	case MULTI_B_PRESSED, GoldenrodCity_RadioTower_2F_EventScript_BuenaDone
# 195 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	end
# 196 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 197 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaPrizeQuickBall::
# 198 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	setvar VAR_0x8008, ITEM_QUICK_BALL
# 199 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	setvar VAR_0x8009, 1
# 200 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaConfirmPrize
# 201 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 202 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaPrizeFullRestore::
# 203 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	setvar VAR_0x8008, ITEM_FULL_RESTORE
# 204 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	setvar VAR_0x8009, 2
# 205 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaConfirmPrize
# 206 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 207 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaPrizeElixir::
# 208 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	setvar VAR_0x8008, ITEM_ELIXIR
# 209 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	setvar VAR_0x8009, 2
# 210 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaConfirmPrize
# 211 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 212 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaPrizeMaxElixir::
# 213 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	setvar VAR_0x8008, ITEM_MAX_ELIXIR
# 214 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	setvar VAR_0x8009, 3
# 215 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaConfirmPrize
# 216 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 217 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaPrizeNugget::
# 218 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	setvar VAR_0x8008, ITEM_NUGGET
# 219 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	setvar VAR_0x8009, 3
# 220 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaConfirmPrize
# 221 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 222 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaPrizeExpCandyL::
# 223 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	setvar VAR_0x8008, ITEM_EXP_CANDY_L
# 224 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	setvar VAR_0x8009, 4
# 225 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaConfirmPrize
# 226 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 227 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaPrizeEviolite::
# 228 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	setvar VAR_0x8008, ITEM_EVIOLITE
# 229 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	setvar VAR_0x8009, 5
# 230 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaConfirmPrize
# 231 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 232 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaPrizePPMax::
# 233 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	setvar VAR_0x8008, ITEM_PP_MAX
# 234 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	setvar VAR_0x8009, 6
# 235 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaConfirmPrize
# 236 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 237 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaPrizeAbilityPatch::
# 238 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	setvar VAR_0x8008, ITEM_ABILITY_PATCH
# 239 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	setvar VAR_0x8009, 7
# 240 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaConfirmPrize
# 241 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 242 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaConfirmPrize::
# 243 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	bufferitemname STR_VAR_1, VAR_0x8008
# 244 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	buffernumberstring STR_VAR_2, VAR_0x8009
# 245 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_BuenaConfirmPrize, MSGBOX_YESNO
# 246 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto_if_eq VAR_RESULT, NO, GoldenrodCity_RadioTower_2F_EventScript_BuenaPrizeMenu
# 247 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto_if_lt VAR_BUENA_POINTS, VAR_0x8009, GoldenrodCity_RadioTower_2F_EventScript_BuenaNotEnoughPoints
# 248 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	checkitemspace VAR_0x8008
# 249 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto_if_eq VAR_RESULT, FALSE, GoldenrodCity_RadioTower_2F_EventScript_BuenaBagFull
# 250 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	giveitem VAR_0x8008
# 251 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto_if_eq VAR_RESULT, FALSE, GoldenrodCity_RadioTower_2F_EventScript_BuenaBagFull
# 252 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	subvar VAR_BUENA_POINTS, VAR_0x8009
# 253 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	buffernumberstring STR_VAR_1, VAR_BUENA_POINTS
# 254 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_BuenaPrizeGiven, MSGBOX_YESNO
# 255 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto_if_eq VAR_RESULT, YES, GoldenrodCity_RadioTower_2F_EventScript_BuenaPrizeMenu
# 256 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaDone
# 257 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 258 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaNotEnoughPoints::
# 259 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_BuenaNotEnoughPoints, MSGBOX_DEFAULT
# 260 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaPrizeMenu
# 261 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 262 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaBagFull::
# 263 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_BuenaBagFull, MSGBOX_DEFAULT
# 264 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto GoldenrodCity_RadioTower_2F_EventScript_BuenaDone
# 265 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 266 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_BuenaDone::
# 267 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	closemessage
# 268 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	release
# 269 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	end
# 270 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 271 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 272 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_Teacher::
# 273 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	lock
# 274 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	faceplayer
# 275 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto_if_eq VAR_GOLDENROD_CITY_STATE, 6, GoldenrodCity_RadioTower_2F_EventScript_Teacher2
# 276 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto_if_eq VAR_GOLDENROD_CITY_STATE, 7, GoldenrodCity_RadioTower_2F_EventScript_Teacher2 
# 277 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto_if_eq VAR_GOLDENROD_CITY_STATE, 8, GoldenrodCity_RadioTower_2F_EventScript_Teacher2 
# 278 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto_if_eq VAR_GOLDENROD_CITY_STATE, 9, GoldenrodCity_RadioTower_2F_EventScript_Teacher2 
# 279 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_Teacher, MSGBOX_DEFAULT
# 280 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	closemessage
# 281 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	release
# 282 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	end
# 283 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 284 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_Teacher2::
# 285 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_TeacherRockets, MSGBOX_DEFAULT
# 286 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	closemessage
# 287 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	release
# 288 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	end
# 289 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 290 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_EventScript_Jigglypuff::
# 291 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	lock
# 292 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	faceplayer
# 293 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	waitse
# 294 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	playmoncry SPECIES_JIGGLYPUFF, CRY_MODE_NORMAL
# 295 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_Text_Jigglypuff, MSGBOX_DEFAULT
# 296 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	waitmoncry
# 297 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	release
# 298 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	end
# 299 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 300 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
RadioTower2FBuenaPasswordIsHelpText:
# 301 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Buena: Today's password?\n"
# 302 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Help, of course!$"
# 303 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 304 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaGreeting:
# 305 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Buena: Hi! This is the studio\n"
# 306 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "for Buena's Password.\p"
# 307 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "What can I do for you?$"
# 308 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 309 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaMenuPassword:
# 310 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Password$"
# 311 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 312 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaMenuPrizes:
# 313 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Prizes$"
# 314 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 315 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaMenuCancel:
# 316 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Cancel$"
# 317 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 318 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAskPassword:
# 319 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Buena: Thank you for listening\n"
# 320 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "in every day!\p"
# 321 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Do you remember today's\n"
# 322 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "password?$"
# 323 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 324 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaForgotPassword:
# 325 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Buena: Come back after you\n"
# 326 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "listen to my show, OK?\p"
# 327 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Catch ya later!$"
# 328 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 329 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaJoinShow:
# 330 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Buena: Oh, wow! Thank you!\p"
# 331 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "What was your name again?\n"
# 332 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "...{PLAYER}!\p"
# 333 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Come on, {PLAYER}.\n"
# 334 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Join the show.$"
# 335 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 336 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaEveryoneReady:
# 337 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Buena: Everyone ready?\p"
# 338 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "I want to hear you shout out\n"
# 339 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "today's password for {PLAYER}!$"
# 340 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 341 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaCorrect:
# 342 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Buena: Yippee! That's right!\n"
# 343 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "You did tune in!\p"
# 344 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "I'm so happy! You earned one\n"
# 345 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "point! Congratulations!\p"
# 346 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Tune in to my show again\n"
# 347 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "tomorrow!$"
# 348 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 349 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaWrong:
# 350 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Buena: Aww... That's not it...\n"
# 351 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Did you forget the password?$"
# 352 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 353 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaOffAir:
# 354 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Buena: My password show airs\nevery night, 6 PM to midnight!\p"
# 355 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Use your Radio to hear the password,\n"
# 356 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "then come see me here!$"
# 357 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 358 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAlreadyPlayed:
# 359 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Sorry... You get just one\n"
# 360 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "chance each day.\p"
# 361 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Come back tomorrow for\n"
# 362 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "another try!$"
# 363 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 364 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaPrizeIntro:
# 365 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Buena: You have {STR_VAR_1}P.\n"
# 366 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Which prize do you want?$"
# 367 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 368 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaConfirmPrize:
# 369 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Buena: Trade {STR_VAR_2}P for\n"
# 370 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "{STR_VAR_1}?$"
# 371 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 372 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaPrizeGiven:
# 373 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Buena: Here you go!\p"
# 374 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "You have {STR_VAR_1}P left.\p"
# 375 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Want another prize?$"
# 376 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 377 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaNotEnoughPoints:
# 378 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Buena: You need more points for\n"
# 379 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "that prize.$"
# 380 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 381 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaBagFull:
# 382 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Buena: Your Bag is full.\p"
# 383 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Make some room and come back!$"
# 384 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 385 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerCyndaquil:
# 386 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Cyndaquil$"
# 387 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 388 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerTotodile:
# 389 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Totodile$"
# 390 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 391 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerChikorita:
# 392 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Chikorita$"
# 393 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 394 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerPotion:
# 395 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Potion$"
# 396 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 397 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerAntidote:
# 398 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Antidote$"
# 399 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 400 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerParlyzHeal:
# 401 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Parlyz Heal$"
# 402 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 403 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerPokeBall:
# 404 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Poke Ball$"
# 405 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 406 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerGreatBall:
# 407 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Great Ball$"
# 408 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 409 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerUltraBall:
# 410 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Ultra Ball$"
# 411 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 412 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerPikachu:
# 413 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Pikachu$"
# 414 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 415 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerRattata:
# 416 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Rattata$"
# 417 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 418 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerGeodude:
# 419 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Geodude$"
# 420 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 421 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerHoothoot:
# 422 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Hoothoot$"
# 423 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 424 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerSpinarak:
# 425 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Spinarak$"
# 426 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 427 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerDrowzee:
# 428 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Drowzee$"
# 429 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 430 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerNewBarkTown:
# 431 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "New Bark Town$"
# 432 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 433 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerCherrygroveCity:
# 434 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Cherrygrove City$"
# 435 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 436 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerAzaleaTown:
# 437 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Azalea Town$"
# 438 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 439 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerBugPokemon:
# 440 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Bug Pokemon$"
# 441 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 442 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerBirdPokemon:
# 443 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Bird Pokemon$"
# 444 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 445 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerGrassPokemon:
# 446 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Grass Pokemon$"
# 447 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 448 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerTackle:
# 449 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Tackle$"
# 450 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 451 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerGrowl:
# 452 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Growl$"
# 453 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 454 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerMudSlap:
# 455 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Mud-Slap$"
# 456 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 457 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerXAttack:
# 458 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "X Attack$"
# 459 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 460 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerXDefend:
# 461 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "X Defend$"
# 462 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 463 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerXSpeed:
# 464 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "X Speed$"
# 465 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 466 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerPokemonTalk:
# 467 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Pokemon Talk$"
# 468 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 469 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerPokemonMusic:
# 470 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Pokemon Music$"
# 471 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 472 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaAnswerBuenasPassword:
# 473 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Buena's Password$"
# 474 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 475 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaPrizeQuickBall:
# 476 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Quick Ball{CLEAR_TO 0x60}1P$"
# 477 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 478 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaPrizeFullRestore:
# 479 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Full Restore{CLEAR_TO 0x60}2P$"
# 480 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 481 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaPrizeElixir:
# 482 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Elixir{CLEAR_TO 0x60}2P$"
# 483 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 484 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaPrizeMaxElixir:
# 485 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Max Elixir{CLEAR_TO 0x60}3P$"
# 486 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 487 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaPrizeNugget:
# 488 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Nugget{CLEAR_TO 0x60}3P$"
# 489 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 490 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaPrizeExpCandyL:
# 491 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Exp Candy L{CLEAR_TO 0x60}4P$"
# 492 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 493 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaPrizeEviolite:
# 494 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Eviolite{CLEAR_TO 0x60}5P$"
# 495 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 496 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaPrizePPMax:
# 497 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "PP Max{CLEAR_TO 0x60}6P$"
# 498 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 499 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaPrizeAbilityPatch:
# 500 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Ability Patch{CLEAR_TO 0x60}7P$"
# 501 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 502 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_SuperNerd:
# 503 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "You can listen to the radio\n"
# 504 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "anywhere. Tune in!$"
# 505 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 506 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_Policeman:
# 507 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Restricted access beyond this\n"
# 508 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "point.$"
# 509 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 510 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_Teacher:
# 511 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Lullabies on the radio may make\n"
# 512 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Pokémon sleep.$"
# 513 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 514 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_TeacherRockets:
# 515 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Why would they want to take over\n"
# 516 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "the Radio Tower?$"
# 517 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 518 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_Jigglypuff:
# 519 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Jigglypuff: Jiggly…$"
# 520 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 521 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BlackBelt1:
# 522 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Sorry. Authorized personnel only\n"
# 523 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "beyond this point.\p"
# 524 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "It wasn't that way before.\p"
# 525 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "There's something wrong with the\n"
# 526 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Director…$"
# 527 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 528 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BlackBelt2:
# 529 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Feel free to look around anywhere.\p"
# 530 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "The Director is nice again, just\n"
# 531 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "as he was before.$"
# 532 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 533 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_GruntM4Seen:
# 534 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Three years ago, Team Rocket was\n"
# 535 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "forced to disband.\p"
# 536 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "But we're making a comeback here!$"
# 537 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 538 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_GruntM4Beaten:
# 539 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Gwah! Don't get cute!$"
# 540 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 541 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_GruntM4After:
# 542 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "We won't let you ruin our plans\n"
# 543 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "for our comeback!$"
# 544 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 545 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_GruntM5Seen:
# 546 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "We're Team Rocket, the exploiters\n"
# 547 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "of Pokémon!\p"
# 548 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "We love being evil! Scared?$"
# 549 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 550 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_GruntM5Beaten:
# 551 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "You think you're a hero?$"
# 552 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 553 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_GruntM5After:
# 554 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "We're not always evil. We just do\n"
# 555 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "whatever we like.$"
# 556 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 557 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_GruntM6Seen:
# 558 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Hey, hey! Keep out of our way!$"
# 559 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 560 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_GruntM6Beaten:
# 561 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Arggh. I give up.$"
# 562 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 563 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_GruntM6After:
# 564 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Our Executives are trying to take\n"
# 565 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "this place over.\p"
# 566 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "They have some big plan. I wonder\n"
# 567 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "what that is?$"
# 568 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 569 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_GruntF2Seen:
# 570 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Hahaha!\p"
# 571 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "How boring. It was far too easy\n"
# 572 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "to take over this place!\p"
# 573 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Come on, keep me amused!$"
# 574 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 575 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_GruntF2Beaten:
# 576 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Wh-who are you?$"
# 577 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 578 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_GruntF2After:
# 579 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "You beat me, and I won't forget\n"
# 580 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "it!$"
# 581 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 582 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_BuenaShowPromo:
# 583 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Buena: My password show airs\nevery night, 6 PM to midnight!\p"
# 584 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Tune in with your Pokégear,\n"
# 585 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "then come see me here!$"
# 586 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 587 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_SalesSign:
# 588 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "2F Sales$"
# 589 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 590 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_OakTalkSign:
# 591 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Prof. Oak's Pokémon Talk\p"
# 592 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "The Hottest Show on the Air!$"
# 593 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"

# 594 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
GoldenrodCity_RadioTower_2F_Text_PokemonRadioSign:
# 595 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Anywhere, Anytime Pokémon Radio$"

GoldenrodCity_RadioTower_2F_MapScripts::
# 598 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, GoldenrodCity_RadioTower_2F_MapScripts_MAP_SCRIPT_ON_TRANSITION
	.byte 0

GoldenrodCity_RadioTower_2F_MapScripts_MAP_SCRIPT_ON_TRANSITION:
# 599 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto_if_set FLAG_IS_CHAMPION, GoldenrodCity_RadioTower_2F_MapScripts_MAP_SCRIPT_ON_TRANSITION_1
# 602 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	setflag FLAG_HIDE_POSTGAME_OAK
	return

GoldenrodCity_RadioTower_2F_MapScripts_MAP_SCRIPT_ON_TRANSITION_1:
# 600 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	clearflag FLAG_HIDE_POSTGAME_OAK
	return


GoldenrodCity_RadioTower_2F_EventScript_Oak::
# 608 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	lock
# 609 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	faceplayer
# 610 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	specialvar VAR_0x8007, ScriptGetJohtoPokedexInfo
# 611 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	buffernumberstring STR_VAR_1, VAR_0x8005
# 612 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	buffernumberstring STR_VAR_2, VAR_0x8006
# 613 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_EventScript_Oak_Text_0
# 617 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_EventScript_Oak_Text_1
# 621 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	special ShowJohtoPokedexRatingMessage
# 622 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	waitmessage
# 623 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	waitbuttonpress
# 624 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	compare VAR_0x8007, FALSE
	goto_if_eq GoldenrodCity_RadioTower_2F_EventScript_Oak_2
# 629 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	goto_if_set FLAG_ARCEUS_EGG_GIVE, GoldenrodCity_RadioTower_2F_EventScript_Oak_5
# 638 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_EventScript_Oak_Text_3
# 645 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	giveegg SPECIES_ARCEUS
# 646 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	compare VAR_RESULT, MON_CANT_GIVE
	goto_if_eq GoldenrodCity_RadioTower_2F_EventScript_Oak_8
# 656 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	setflag FLAG_ARCEUS_EGG_GIVE
# 657 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	playfanfare MUS_OBTAIN_ITEM
# 658 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	message GoldenrodCity_RadioTower_2F_EventScript_Oak_Text_5
# 660 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	waitfanfare
# 661 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PC
	goto_if_eq GoldenrodCity_RadioTower_2F_EventScript_Oak_11
GoldenrodCity_RadioTower_2F_EventScript_Oak_10:
# 665 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_EventScript_Oak_Text_7
# 667 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	closemessage
# 668 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	release
	end

GoldenrodCity_RadioTower_2F_EventScript_Oak_2:
# 625 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	closemessage
# 626 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	release
	end

GoldenrodCity_RadioTower_2F_EventScript_Oak_5:
# 630 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_EventScript_Oak_Text_2
# 634 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	closemessage
# 635 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	release
	end

GoldenrodCity_RadioTower_2F_EventScript_Oak_8:
# 647 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_EventScript_Oak_Text_4
# 652 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	closemessage
# 653 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	release
	end

GoldenrodCity_RadioTower_2F_EventScript_Oak_11:
# 662 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_2F_EventScript_Oak_Text_6
	goto GoldenrodCity_RadioTower_2F_EventScript_Oak_10


GoldenrodCity_RadioTower_2F_EventScript_Oak_Text_0:
# 613 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Oak: Good to see you, {PLAYER}!\p"
	.string "How is your Pokédex coming along?\n"
	.string "Here, let me take a look.$"

GoldenrodCity_RadioTower_2F_EventScript_Oak_Text_1:
# 617 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "You've seen {STR_VAR_1} Pokémon,\n"
	.string "and you've caught {STR_VAR_2} Pokémon.\p"
	.string "Here is my Johto Pokédex rating:$"

GoldenrodCity_RadioTower_2F_EventScript_Oak_Text_2:
# 630 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Oak: Your completed Johto Pokédex\n"
	.string "fills me with pride.\p"
	.string "Take good care of that Egg!$"

GoldenrodCity_RadioTower_2F_EventScript_Oak_Text_3:
# 638 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Oak: Ah! You've completed the\n"
	.string "Johto Pokédex!\p"
	.string "This is a magnificent feat!\p"
	.string "I want you to have this very\n"
	.string "special Pokémon Egg.$"

GoldenrodCity_RadioTower_2F_EventScript_Oak_Text_4:
# 647 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Oak: Oh! There isn't any room in\n"
	.string "your party or PC.\p"
	.string "Come back after making some space,\n"
	.string "and I'll give you the Egg.$"

GoldenrodCity_RadioTower_2F_EventScript_Oak_Text_5:
# 658 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "{PLAYER} received a Special Egg\n"
	.string "from Prof. Oak!$"

GoldenrodCity_RadioTower_2F_EventScript_Oak_Text_6:
# 662 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Your party was full, so the Egg was\n"
	.string "sent to your PC.$"

GoldenrodCity_RadioTower_2F_EventScript_Oak_Text_7:
# 665 "data/maps/GoldenrodCity_RadioTower_2F/scripts.pory"
	.string "Oak: I can't wait to see what you\n"
	.string "discover. Take good care of it!$"
